name: "dbt_hiive"
version: "1.0.0"

profile: "dbt_hiive"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_hiive:
    marts:
      +materialized: table
    stg_customer_order_summary:
      +enabled: false